---
- name: Restart nginx service
  ansible.builtin.systemd:
    enabled: "yes"
    name: nginx
    state: restarted
- name: Reload nginx service
  ansible.builtin.systemd:
    enabled: "yes"
    name: nginx
    state: reloaded
