---
- name: Reload systemd user daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
- name: Restart Prometheus service
  ansible.builtin.systemd_service:
    enabled: "yes"
    name: prometheus.service
    scope: user
    state: restarted
